# Generated by Django 2.0 on 2018-12-13 07:09

from django.db import migrations, models
import django.db.models.deletion
import myApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alltarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetname', models.CharField(max_length=30, verbose_name='大指标名称')),
            ],
            options={
                'verbose_name': '大指标',
                'verbose_name_plural': '综合大指标',
                'db_table': 'myApp_Alltarget',
            },
        ),
        migrations.CreateModel(
            name='CultivateFactors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoursePractice', models.CharField(choices=[('一般', '一般'), ('满意', '满意'), ('较差', '较差')], max_length=5)),
                ('E_IndustryDynamics', models.CharField(choices=[('从来没有', '从来没有'), ('经常', '经常'), ('偶尔', '偶尔')], max_length=10)),
                ('E_PracticeCombine', models.CharField(choices=[('从来没有', '从来没有'), ('经常', '经常'), ('偶尔', '偶尔')], max_length=10)),
                ('E_UseingCase', models.CharField(choices=[('从来没有', '从来没有'), ('经常', '经常'), ('偶尔', '偶尔')], max_length=10)),
                ('E_DifferentActivity', models.CharField(choices=[('从来没有', '从来没有'), ('经常', '经常'), ('偶尔', '偶尔')], max_length=10)),
                ('F_IndustryDynamics', models.CharField(choices=[('从来没有', '从来没有'), ('经常', '经常'), ('偶尔', '偶尔')], max_length=10)),
                ('F_PracticeCombine', models.CharField(choices=[('从来没有', '从来没有'), ('经常', '经常'), ('偶尔', '偶尔')], max_length=10)),
                ('F_UseingCase', models.CharField(choices=[('从来没有', '从来没有'), ('经常', '经常'), ('偶尔', '偶尔')], max_length=10)),
                ('F_DifferentActivity', models.CharField(choices=[('从来没有', '从来没有'), ('经常', '经常'), ('偶尔', '偶尔')], max_length=10)),
                ('F_TraditionClass', models.CharField(choices=[('从来没有', '从来没有'), ('经常', '经常'), ('偶尔', '偶尔')], max_length=10)),
                ('F_CourseEffect', models.CharField(choices=[('没有效果', '没有效果'), ('很好', '很好'), ('一般', '一般')], max_length=10)),
                ('I_TeacherDirect', models.CharField(choices=[('没有效果', '没有效果'), ('很好', '很好'), ('一般', '一般')], max_length=10)),
                ('O_TeacherDirect', models.CharField(choices=[('没有效果', '没有效果'), ('很好', '很好'), ('一般', '一般')], max_length=10)),
                ('I_TeacherAbility', models.CharField(choices=[('没有效果', '没有效果'), ('很好', '很好'), ('一般', '一般')], max_length=10)),
                ('O_TeacherAbility', models.CharField(choices=[('没有效果', '没有效果'), ('很好', '很好'), ('一般', '一般')], max_length=10)),
                ('ThesisCombinePractice', models.CharField(choices=[('没有联系', '没有联系'), ('联系一般', '联系一般'), ('联系紧密', '联系紧密')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Factors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factorname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Postgraduates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.CharField(max_length=50)),
                ('Pname', models.CharField(max_length=50)),
                ('Ppassword', models.CharField(max_length=50)),
                ('Pgender', models.BooleanField(default=True)),
                ('Pgrade', models.IntegerField()),
                ('Pdegree', models.CharField(max_length=50)),
                ('Pexperience', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PostgraduatesHomework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phomework', models.FileField(upload_to=myApp.models.upload_to2)),
                ('student_id', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=50)),
                ('postgraduates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Postgraduates')),
            ],
        ),
        migrations.CreateModel(
            name='PostgraduatesTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ptest', models.FileField(upload_to=myApp.models.upload_to1)),
                ('student_id', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=50)),
                ('postgraduates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Postgraduates')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessPracticeFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PracticeBeginTime', models.CharField(max_length=50)),
                ('ContinueTime', models.CharField(max_length=50)),
                ('ActivityFrequency', models.CharField(choices=[('从来没有', '从来没有'), ('经常', '经常'), ('偶尔', '偶尔')], max_length=10)),
                ('ActivityContent', models.CharField(choices=[('没有系统性', '没有系统性'), ('内容系统性一般', '内容系统性一般'), ('内容系统性较好', '内容系统性较好')], max_length=10)),
                ('ActivitySatisfy', models.CharField(choices=[('一般', '一般'), ('满意', '满意'), ('较差', '较差')], max_length=10)),
                ('ActivityEffect', models.CharField(choices=[('没有效果', '没有效果'), ('很好', '很好'), ('一般', '一般')], max_length=10)),
                ('postgraduates', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myApp.Postgraduates')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFactorsvalue1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factorsvalue', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFactorsvalue2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factorsvalue', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFactorsvalue3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factorsvalue', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentselfAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('postgraduates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Postgraduates')),
            ],
        ),
        migrations.CreateModel(
            name='Sub1Factors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factorname', models.CharField(max_length=30)),
                ('isvalue', models.BooleanField(default=False)),
                ('value', models.CharField(max_length=30, null=True)),
                ('factors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Factors')),
            ],
        ),
        migrations.CreateModel(
            name='Sub2Factors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factorname', models.CharField(max_length=30)),
                ('isvalue', models.BooleanField(default=False)),
                ('value', models.CharField(max_length=30, null=True)),
                ('factors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Sub1Factors')),
            ],
        ),
        migrations.CreateModel(
            name='Sub3Factors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factorname', models.CharField(max_length=30)),
                ('isvalue', models.BooleanField(default=False)),
                ('value', models.CharField(max_length=30, null=True)),
                ('factors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Sub2Factors')),
            ],
        ),
        migrations.CreateModel(
            name='Subtarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetname', models.CharField(max_length=30, verbose_name='小指标名称')),
                ('alltarget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Alltarget', verbose_name='大指标名称')),
            ],
            options={
                'verbose_name': '小指标',
                'verbose_name_plural': '综合小指标',
                'db_table': 'myApp_Subtarget',
            },
        ),
        migrations.CreateModel(
            name='TeacherAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('targetname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Subtarget')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tid', models.CharField(max_length=50)),
                ('Tname', models.CharField(max_length=50)),
                ('Tweight', models.FloatField()),
                ('Tpassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeachertoStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('postgraduates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Postgraduates')),
                ('targetname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Subtarget')),
                ('teahcers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Teachers')),
            ],
        ),
        migrations.AddField(
            model_name='teacheraccess',
            name='teahcers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Teachers'),
        ),
        migrations.AddField(
            model_name='studentselfaccess',
            name='targetname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Subtarget'),
        ),
        migrations.AddField(
            model_name='studentfactorsvalue3',
            name='factorsattribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Sub3Factors'),
        ),
        migrations.AddField(
            model_name='studentfactorsvalue3',
            name='postgraduates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Postgraduates'),
        ),
        migrations.AddField(
            model_name='studentfactorsvalue2',
            name='factorsattribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Sub2Factors'),
        ),
        migrations.AddField(
            model_name='studentfactorsvalue2',
            name='postgraduates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Postgraduates'),
        ),
        migrations.AddField(
            model_name='studentfactorsvalue1',
            name='factorsattribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Sub1Factors'),
        ),
        migrations.AddField(
            model_name='studentfactorsvalue1',
            name='postgraduates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Postgraduates'),
        ),
        migrations.AddField(
            model_name='cultivatefactors',
            name='postgraduates',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myApp.Postgraduates'),
        ),
    ]
