# Generated by Django 2.0 on 2018-12-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alltarget',
            options={'verbose_name': '大指标', 'verbose_name_plural': '综合大指标管理'},
        ),
        migrations.AlterModelOptions(
            name='businesstostudentfactors',
            options={'verbose_name': '单位评价指标', 'verbose_name_plural': '单位评价指标管理'},
        ),
        migrations.AlterModelOptions(
            name='studentfactorsvalue1',
            options={'verbose_name': '一级因素评分', 'verbose_name_plural': '一级因素评分管理'},
        ),
        migrations.AlterModelOptions(
            name='studentfactorsvalue2',
            options={'verbose_name': '二级因素评分', 'verbose_name_plural': '二级因素评分管理'},
        ),
        migrations.AlterModelOptions(
            name='studentfactorsvalue3',
            options={'verbose_name': '三级因素评分', 'verbose_name_plural': '三级因素评分管理'},
        ),
        migrations.AlterModelOptions(
            name='studentselfaccess',
            options={'verbose_name': '学生自评分数', 'verbose_name_plural': '学生自评分数管理'},
        ),
        migrations.AlterModelOptions(
            name='studentselfaccessfactors',
            options={'verbose_name': '学生自评指标', 'verbose_name_plural': '学生自评指标管理'},
        ),
        migrations.AlterModelOptions(
            name='studenttostudentfactors',
            options={'verbose_name': '学生互评指标', 'verbose_name_plural': '学生互评指标管理'},
        ),
        migrations.AlterModelOptions(
            name='subtarget',
            options={'verbose_name': '小指标', 'verbose_name_plural': '综合小指标管理'},
        ),
        migrations.AlterModelOptions(
            name='teacheraccess',
            options={'verbose_name': '教师评分', 'verbose_name_plural': '教师评分管理'},
        ),
        migrations.AlterModelOptions(
            name='teachertostudentfactors',
            options={'verbose_name': '教师评价指标', 'verbose_name_plural': '教师评价指标管理'},
        ),
        migrations.AlterModelOptions(
            name='zhuanjiatostudentfactors',
            options={'verbose_name': '专家评价指标', 'verbose_name_plural': '专家评价指标管理'},
        ),
        migrations.RenameField(
            model_name='studenttostudentscore',
            old_name='self',
            new_name='himself',
        ),
        migrations.AlterModelTable(
            name='businesstostudentfactors',
            table='myapp_BusinesstoStudentFactors',
        ),
        migrations.AlterModelTable(
            name='studentselfaccessfactors',
            table='myapp_StudentselfAccessFactors',
        ),
        migrations.AlterModelTable(
            name='studenttostudentfactors',
            table='myapp_StudenttoStudentFactors',
        ),
        migrations.AlterModelTable(
            name='teachertostudentfactors',
            table='myapp_TeachertoStudentFactors',
        ),
        migrations.AlterModelTable(
            name='zhuanjiatostudentfactors',
            table='myapp_ZhuanjiatoStudentFactors',
        ),
    ]
