# Generated by Django 2.0 on 2018-12-19 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivatefactors',
            name='postgraduates',
        ),
        migrations.RemoveField(
            model_name='professpracticefactor',
            name='postgraduates',
        ),
        migrations.AlterModelOptions(
            name='factors',
            options={'verbose_name': '综合培养因素', 'verbose_name_plural': '综合培养因素管理'},
        ),
        migrations.AlterModelOptions(
            name='postgraduates',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生用户管理'},
        ),
        migrations.AlterModelOptions(
            name='studentfactorsvalue1',
            options={'verbose_name': '一级因素评分', 'verbose_name_plural': '一级因素评分'},
        ),
        migrations.AlterModelOptions(
            name='studentfactorsvalue2',
            options={'verbose_name': '二级因素评分', 'verbose_name_plural': '二级因素评分'},
        ),
        migrations.AlterModelOptions(
            name='studentfactorsvalue3',
            options={'verbose_name': '三级因素评分', 'verbose_name_plural': '三级因素评分'},
        ),
        migrations.AlterModelOptions(
            name='studentselfaccess',
            options={'verbose_name': '学生自评分数', 'verbose_name_plural': '学生自评分数'},
        ),
        migrations.AlterModelOptions(
            name='sub1factors',
            options={'verbose_name': '一综合养因素', 'verbose_name_plural': '一级综合因素管理'},
        ),
        migrations.AlterModelOptions(
            name='sub2factors',
            options={'verbose_name': '二级综合因素', 'verbose_name_plural': '二级综合因素管理'},
        ),
        migrations.AlterModelOptions(
            name='sub3factors',
            options={'verbose_name': '三级综合因素', 'verbose_name_plural': '三级综合因素管理'},
        ),
        migrations.AlterModelOptions(
            name='teacheraccess',
            options={'verbose_name': '教师评分', 'verbose_name_plural': '教师评分'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': '教师', 'verbose_name_plural': '教师用户管理'},
        ),
        migrations.AlterModelOptions(
            name='teachertostudent',
            options={'verbose_name': '教师对学生评分管理', 'verbose_name_plural': '教师对学生评分管理'},
        ),
        migrations.AlterField(
            model_name='postgraduates',
            name='Pdegree',
            field=models.CharField(max_length=50, verbose_name='专业学位'),
        ),
        migrations.AlterField(
            model_name='postgraduates',
            name='Pexperience',
            field=models.CharField(max_length=50, verbose_name='工作经历'),
        ),
        migrations.AlterField(
            model_name='postgraduates',
            name='Pgender',
            field=models.BooleanField(default=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='postgraduates',
            name='Pgrade',
            field=models.IntegerField(verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='postgraduates',
            name='Pid',
            field=models.CharField(max_length=50, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='postgraduates',
            name='Pname',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='postgraduates',
            name='Ppassword',
            field=models.CharField(max_length=50, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='studentfactorsvalue1',
            name='factorsattribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Sub1Factors', verbose_name='所属因素'),
        ),
        migrations.AlterField(
            model_name='studentfactorsvalue1',
            name='factorsvalue',
            field=models.CharField(max_length=30, verbose_name='评价'),
        ),
        migrations.AlterField(
            model_name='studentfactorsvalue2',
            name='factorsattribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Sub2Factors', verbose_name='所属因素'),
        ),
        migrations.AlterField(
            model_name='studentfactorsvalue2',
            name='factorsvalue',
            field=models.CharField(max_length=30, verbose_name='评价'),
        ),
        migrations.AlterField(
            model_name='studentfactorsvalue3',
            name='factorsattribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Sub3Factors', verbose_name='所属因素'),
        ),
        migrations.AlterField(
            model_name='studentfactorsvalue3',
            name='factorsvalue',
            field=models.CharField(max_length=30, verbose_name='评价'),
        ),
        migrations.AlterField(
            model_name='studentselfaccess',
            name='score',
            field=models.IntegerField(null=True, verbose_name='小指标分数'),
        ),
        migrations.AlterField(
            model_name='studentselfaccess',
            name='targetname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Subtarget', verbose_name='所属小指标'),
        ),
        migrations.AlterField(
            model_name='sub1factors',
            name='factorname',
            field=models.CharField(max_length=30, verbose_name='一级因素名称'),
        ),
        migrations.AlterField(
            model_name='sub1factors',
            name='factors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Factors', verbose_name='所属因素'),
        ),
        migrations.AlterField(
            model_name='sub1factors',
            name='value',
            field=models.CharField(max_length=30, null=True, verbose_name='选项值'),
        ),
        migrations.AlterField(
            model_name='sub2factors',
            name='factorname',
            field=models.CharField(max_length=30, verbose_name='二级因素名称'),
        ),
        migrations.AlterField(
            model_name='sub2factors',
            name='factors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Sub1Factors', verbose_name='所属因素'),
        ),
        migrations.AlterField(
            model_name='sub2factors',
            name='value',
            field=models.CharField(max_length=30, null=True, verbose_name='选项值'),
        ),
        migrations.AlterField(
            model_name='sub3factors',
            name='factorname',
            field=models.CharField(max_length=30, verbose_name='三级因素名称'),
        ),
        migrations.AlterField(
            model_name='sub3factors',
            name='factors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Sub2Factors', verbose_name='所属因素'),
        ),
        migrations.AlterField(
            model_name='sub3factors',
            name='value',
            field=models.CharField(max_length=30, null=True, verbose_name='选项值'),
        ),
        migrations.AlterField(
            model_name='teacheraccess',
            name='score1',
            field=models.IntegerField(null=True, verbose_name='分数1'),
        ),
        migrations.AlterField(
            model_name='teacheraccess',
            name='score2',
            field=models.IntegerField(null=True, verbose_name='分数2'),
        ),
        migrations.AlterField(
            model_name='teacheraccess',
            name='targetname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Subtarget', verbose_name='小指标'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='Tname',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='Tpassword',
            field=models.CharField(max_length=50, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='Tweight',
            field=models.FloatField(verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='teachertostudent',
            name='postgraduates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Postgraduates', verbose_name='学生名称'),
        ),
        migrations.AlterField(
            model_name='teachertostudent',
            name='score',
            field=models.IntegerField(null=True, verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='teachertostudent',
            name='targetname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Subtarget', verbose_name='指标名称'),
        ),
        migrations.AlterField(
            model_name='teachertostudent',
            name='teahcers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Teachers', verbose_name='教师名称'),
        ),
        migrations.AlterModelTable(
            name='factors',
            table='myApp_Factors',
        ),
        migrations.AlterModelTable(
            name='postgraduates',
            table='myApp_Postgraduates',
        ),
        migrations.AlterModelTable(
            name='studentfactorsvalue1',
            table='myApp_StudentFactorsvalue1',
        ),
        migrations.AlterModelTable(
            name='studentfactorsvalue2',
            table='myApp_StudentFactorsvalue2',
        ),
        migrations.AlterModelTable(
            name='studentfactorsvalue3',
            table='myApp_StudentFactorsvalue3',
        ),
        migrations.AlterModelTable(
            name='studentselfaccess',
            table='myApp_StudentselfAccess',
        ),
        migrations.AlterModelTable(
            name='sub1factors',
            table='myApp_Sub1Factors',
        ),
        migrations.AlterModelTable(
            name='sub2factors',
            table='myApp_Sub2Factors',
        ),
        migrations.AlterModelTable(
            name='sub3factors',
            table='myApp_Sub3Factors',
        ),
        migrations.AlterModelTable(
            name='teacheraccess',
            table='myApp_TeacherAccess',
        ),
        migrations.AlterModelTable(
            name='teachers',
            table='myApp_Teachers',
        ),
        migrations.AlterModelTable(
            name='teachertostudent',
            table='myApp_TeachertoStudent',
        ),
        migrations.DeleteModel(
            name='CultivateFactors',
        ),
        migrations.DeleteModel(
            name='ProfessPracticeFactor',
        ),
    ]
