# Generated by Django 2.0 on 2018-12-27 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20181226_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstostudentscore',
            name='targetname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.BusinesstoStudentFactors', verbose_name='指标名称'),
        ),
    ]
