# Generated by Django 2.0 on 2019-01-03 05:38

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20181227_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.FileField(upload_to=myapp.models.upload_to3, verbose_name='案例')),
                ('name', models.CharField(max_length=30, verbose_name='文件名')),
            ],
        ),
        migrations.CreateModel(
            name='CaseName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casename', models.CharField(max_length=30, verbose_name='案例种类')),
            ],
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': '企业', 'verbose_name_plural': '企业用户管理'},
        ),
        migrations.AlterModelOptions(
            name='businesstostudentscore',
            options={'verbose_name': '企业评分分数', 'verbose_name_plural': '企业评价分数管理'},
        ),
        migrations.AlterModelOptions(
            name='postgraduateshomework',
            options={'verbose_name': '作业', 'verbose_name_plural': '学生作业管理'},
        ),
        migrations.AlterModelOptions(
            name='postgraduatestest',
            options={'verbose_name': '论文', 'verbose_name_plural': '学生论文管理'},
        ),
        migrations.AlterModelOptions(
            name='studenttostudentscore',
            options={'verbose_name': '学生互评分数', 'verbose_name_plural': '学生互评分数管理'},
        ),
        migrations.AlterModelOptions(
            name='zhuanjia',
            options={'verbose_name': '专家', 'verbose_name_plural': '专家用户管理'},
        ),
        migrations.AlterModelOptions(
            name='zhuanjiatostudentscore',
            options={'verbose_name': '专家评分分数', 'verbose_name_plural': '专家评价分数管理'},
        ),
        migrations.AlterField(
            model_name='business',
            name='Bid',
            field=models.CharField(max_length=50, verbose_name='企业账号id'),
        ),
        migrations.AlterField(
            model_name='business',
            name='Bname',
            field=models.CharField(max_length=50, verbose_name='企业名称'),
        ),
        migrations.AlterField(
            model_name='postgraduateshomework',
            name='Phomework',
            field=models.FileField(upload_to=myapp.models.upload_to2, verbose_name='论文'),
        ),
        migrations.AlterField(
            model_name='postgraduateshomework',
            name='name',
            field=models.CharField(max_length=50, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='postgraduateshomework',
            name='student_id',
            field=models.CharField(max_length=25, verbose_name='学生id'),
        ),
        migrations.AlterField(
            model_name='postgraduatestest',
            name='Ptest',
            field=models.FileField(upload_to=myapp.models.upload_to1, verbose_name='论文'),
        ),
        migrations.AlterField(
            model_name='postgraduatestest',
            name='name',
            field=models.CharField(max_length=50, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='postgraduatestest',
            name='student_id',
            field=models.CharField(max_length=25, verbose_name='学生id'),
        ),
        migrations.AlterField(
            model_name='zhuanjia',
            name='Zid',
            field=models.CharField(max_length=50, verbose_name='专家账号id'),
        ),
        migrations.AlterModelTable(
            name='business',
            table='myapp_Business',
        ),
        migrations.AlterModelTable(
            name='businesstostudentscore',
            table='myapp_BusinesstoStudentScore',
        ),
        migrations.AlterModelTable(
            name='factors',
            table='myapp_Factors',
        ),
        migrations.AlterModelTable(
            name='postgraduateshomework',
            table='myapp_PostgraduatesHomework',
        ),
        migrations.AlterModelTable(
            name='postgraduatestest',
            table='myapp_PostgraduatesTest',
        ),
        migrations.AlterModelTable(
            name='studenttostudentscore',
            table='myapp_StudenttoStudentScore',
        ),
        migrations.AlterModelTable(
            name='sub1factors',
            table='myapp_Sub1Factors',
        ),
        migrations.AlterModelTable(
            name='zhuanjia',
            table='myapp_Zhuanjia',
        ),
        migrations.AlterModelTable(
            name='zhuanjiatostudentscore',
            table='myapp_ZhuanjiatoStudentScore',
        ),
        migrations.AddField(
            model_name='caseanalysis',
            name='attrcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.CaseName'),
        ),
    ]
