# Generated by Django 2.0 on 2019-01-04 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190103_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseanalysis',
            options={'verbose_name': '案例', 'verbose_name_plural': '案例管理'},
        ),
        migrations.AlterModelOptions(
            name='casename',
            options={'verbose_name': '案例', 'verbose_name_plural': '案例管理'},
        ),
        migrations.RenameField(
            model_name='subtarget',
            old_name='targetexplain',
            new_name='targetextplain',
        ),
        migrations.AlterModelTable(
            name='caseanalysis',
            table='myapp_CaseAnalysis',
        ),
        migrations.AlterModelTable(
            name='casename',
            table='myapp_CaseName',
        ),
    ]
